# Generated by Django 4.0 on 2022-01-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='snippet',
            new_name='preview',
        ),
    ]
