# Generated by Django 4.0 on 2022-01-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_rename_snippet_post_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(max_length=255),
        ),
    ]
